services:
    postgresql:
        image: postgres:13.1
        environment:
            - POSTGRES_USER=statsservice
            - POSTGRES_PASSWORD=PizzaMargaritaRocks
        ports:
            - 5432:5432
        volumes:
            - postgresql-data:/var/lib/postgresql/data
volumes:
    postgresql-data:
